//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguist.MSBuild.Demo {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up and formatting localized strings, etc.
    /// </summary>
    /// <remarks>
    /// This class was auto-generated by the Linguist.Generator.ResourceTypeBuilder class via the
    /// Localization custom tool.
    /// To add or remove a member, edit your .ResX file then rerun the Localization custom tool or rebuild
    /// your VS project.
    /// </remarks>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Linguist.Generator.ResourceTypeBuilder", "0.9.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
    public static partial class Resources {
        
        private static global::System.Globalization.CultureInfo _culture;
        
        /// <summary>
        /// Returns the cached Localizer instance used by this class.
        /// </summary>
        internal static global::Linguist.Resources.ResourceManagerLocalizer Localizer {
            get {
                return _localizer.Value;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                return _resourceManager.Value;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all resource lookups using this
        /// strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _culture;
            }
            set {
                if (object.Equals(_culture, value)) {
                    return;
                }
                _culture = value;
                NotifyCultureChanged();
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Hello World!'.
        /// </summary>
        internal static string HelloWorld {
            get {
                return Localizer.GetString(_culture, "HelloWorld");
            }
        }
        
        /// <summary>
        /// Looks up a resource 'Image'.
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                return ((System.Drawing.Bitmap)(Localizer.GetObject(_culture, "Image")));
            }
        }
        
        public static event global::System.ComponentModel.PropertyChangedEventHandler StaticPropertyChanged;
        
        internal static void NotifyCultureChanged() {
            global::System.ComponentModel.PropertyChangedEventHandler notify = StaticPropertyChanged;
            if ((notify == null)) {
                return;
            }
            notify(null, new global::System.ComponentModel.PropertyChangedEventArgs(null));
        }
        
        public static class _resourceManager {
            
            internal static global::System.Resources.ResourceManager Value = new global::System.Resources.ResourceManager("Linguist.MSBuild.Demo.Resources", typeof(Resources).Assembly, typeof(global::Linguist.Resources.Binary.BinaryResourceSet));
            
            // Explicit static constructor to tell compiler not to mark type as beforefieldinit
            static _resourceManager() {
            }
        }
        
        public static class _localizer {
            
            internal static global::Linguist.Resources.ResourceManagerLocalizer Value = new global::Linguist.Resources.ResourceManagerLocalizer(ResourceManager);
            
            // Explicit static constructor to tell compiler not to mark type as beforefieldinit
            static _localizer() {
            }
        }
    }
}
